### PR TITLE
SHE-5: ComScore Integration for Android

### PR DESCRIPTION
**Pull request by hoonboon**
Added ComScore integration for Android platform.

For testing, please install the ComScore plugin to the ionic project first:
```
$ ionic plugin add https://github.com/fourmisolutions/cordova-comscore-plugin
```

Refer to "Chapter 3: Test Your Implementation" in the attached ComScore implementation specifications PDF file to perform the recommended test.

[comScoreImplementationSpecs-Android.pdf](https://github.com/fourmisolutions/epaper/files/1011451/comScoreImplementationSpecs-Android.pdf)

### CODE REVIEW

**Review by hutingung — COMMENTED** [review]
Hoon Boon,

Changes looks good. 

I have a query. How comscore different access to different screen of mobile app? or it doesn't care?

**Comment by hoonboon** [comment]
TingUng,

Attached are screen shots of sample HTTP GET that the ComScore client within the mobile app will send over to the ComScore server:

comscore_samplehttpget_01
comscore_samplehttpget_02


I do not have the full documentation on what each of the query string field represents but I believed the query string field "ns_ap_res" or "ns_ap_sd" is being used to store the device screen resolution.

**Comment by hoonboon** [comment]
Ting Ung 

Sorry, I might have misunderstood your question.

If your "different screen of mobile app" refers to the "different modules or pages within the same mobile app", then I think the ComScore client does not send over such data to the server (referring to the screen shots provided above).

Based on my observations, the ComScore client simply record the user session data for the particular app from the moment the app is started till it is closed (removed from background).

The ComScore client only send out the HTTP GET request to the server once when the app is started.

**Comment by hoonboon** [comment]
If the client requires tracking of different modules within the app and is certain that the ComScore client is capable of doing it, you might want to consider getting the client to provide us the full documentation of the SDK or specific instructions on how it can be done.

The documents provided so far do not contain such info.

**Comment by hoonboon** [comment]
TingUng

After playing around with the ComScore Analytics class, I might have found a way to trigger some event notification which will be sent over to the ComScore server each time the event is triggered.

This might be a way to capture screen view data, but I do not know what is the correct way to define the event info data so that it could be captured, processed and displayed correctly in the ComScore statistics/ reports.

Will need to check with the client and/ or ComScore support to define how the Event Info should be set.

Below are the screen shots of the HTTP GET request of the screen viewing event generated from my testing:

Breaking News screen view:
comscore_sample_eventbreakingnews_01
comscore_sample_eventbreakingnews_02

Daily News screen view:
comscore_sample_eventdailynews_01
comscore_sample_eventdailynews_02

**Comment by hutingung** [comment]
Hoon Boon,

Your research looks good. 

Attached is the report I have downloaded from comscore for your reference. Is it related to your test?

[Tag_Review_MobileApps_All.zip](https://github.com/fourmisolutions/epaper/files/1016800/Tag_Review_MobileApps_All.zip)

**Comment by hoonboon** [comment]
TingUng

The attached report only contains statistics for "App Start" event.

I do not see anything relating to the screen view event.

You have access to the client's ComScore account to view reports?

**Comment by hutingung** [comment]
Just to end the discussion. I have given the credentials to Hoon Boon.

**Pull request merged**
